//! Physics fault model abstraction and factory helpers.
//!
//! This module defines the common trait used by physics fault models,
//! their configuration enum, and helper functions to instantiate runtime implementations.
//! Currently, the main implementation is [`AdditiveRobotCenteredPhysicsFault`].

use std::{fmt::Debug, sync::Arc};

use simba_macros::config_derives;

use crate::{
    errors::SimbaResult,
    physics::{
        fault_models::additive_robot_centered::{
            AdditiveRobotCenteredPhysicsFault, AdditiveRobotCenteredPhysicsFaultConfig,
        },
        robot_models::RobotModelConfig,
    },
    state_estimators::State,
    utils::determinist_random_variable::DeterministRandomVariableFactory,
};
#[cfg(feature = "gui")]
use crate::{gui::UIComponent, simulator::SimulatorConfig};

/// Configuration enum for physics fault models.
///
/// Default value (generated by `#[config_derives]`):
/// [`PhysicsFaultModelConfig::AdditiveRobotCentered`] with
/// [`AdditiveRobotCenteredPhysicsFaultConfig::default`].
#[config_derives]
pub enum PhysicsFaultModelConfig {
    /// Additive physics fault model in robot-centered coordinates.
    #[check]
    AdditiveRobotCentered(AdditiveRobotCenteredPhysicsFaultConfig),
}

#[cfg(feature = "gui")]
impl UIComponent for PhysicsFaultModelConfig {
    fn show_mut(
        &mut self,
        ui: &mut egui::Ui,
        ctx: &egui::Context,
        buffer_stack: &mut std::collections::BTreeMap<String, String>,
        global_config: &SimulatorConfig,
        current_node_name: Option<&String>,
        unique_id: &str,
    ) {
        let self_str = self.to_string();
        egui::CollapsingHeader::new(self_str)
            .id_salt(format!("physics-fault-model-{}", unique_id))
            .show(ui, |ui| {
                match self {
                    Self::AdditiveRobotCentered(cfg) => cfg.show_mut(
                        ui,
                        ctx,
                        buffer_stack,
                        global_config,
                        current_node_name,
                        unique_id,
                    ),
                };
            });
    }

    fn show(&self, ui: &mut egui::Ui, ctx: &egui::Context, unique_id: &str) {
        let self_str = self.to_string();
        egui::CollapsingHeader::new(self_str)
            .id_salt(format!("physics-fault-model-{}", unique_id))
            .show(ui, |ui| {
                match self {
                    Self::AdditiveRobotCentered(cfg) => cfg.show(ui, ctx, unique_id),
                };
            });
    }
}

#[cfg(feature = "gui")]
impl PhysicsFaultModelConfig {
    /// Renders mutable GUI controls for a list of physics fault model configurations.
    pub fn show_faults_mut(
        faults: &mut Vec<PhysicsFaultModelConfig>,
        ui: &mut egui::Ui,
        ctx: &egui::Context,
        buffer_stack: &mut std::collections::BTreeMap<String, String>,
        global_config: &SimulatorConfig,
        current_node_name: Option<&String>,
        unique_id: &str,
    ) {
        use crate::{gui::utils::string_combobox, utils::enum_tools::ToVec};

        ui.label("Faults:");
        let mut fault_to_remove = None;
        for (i, fault) in faults.iter_mut().enumerate() {
            ui.horizontal_top(|ui| {
                let unique_fault_id = format!("physics-fault-{i}-{unique_id}");
                fault.show_mut(
                    ui,
                    ctx,
                    buffer_stack,
                    global_config,
                    current_node_name,
                    &unique_fault_id,
                );

                if ui.button("X").clicked() {
                    fault_to_remove = Some(i);
                }
            });
        }
        if let Some(i) = fault_to_remove {
            faults.remove(i);
        }

        ui.horizontal(|ui| {
            let buffer_key = format!("selected-new-physics-fault-{unique_id}");
            if !buffer_stack.contains_key(&buffer_key) {
                buffer_stack.insert(buffer_key.clone(), "AdditiveRobotCentered".to_string());
            }
            string_combobox(
                ui,
                &PhysicsFaultModelConfig::to_vec(),
                buffer_stack.get_mut(&buffer_key).unwrap(),
                format!("physics-fault-choice-{}", unique_id),
            );
            if ui.button("Add").clicked() {
                let selected_fault = buffer_stack.get(&buffer_key).unwrap();
                match selected_fault.as_str() {
                    "AdditiveRobotCentered" => {
                        use crate::physics::fault_models::additive_robot_centered::AdditiveRobotCenteredPhysicsFaultConfig;

                        faults.push(PhysicsFaultModelConfig::AdditiveRobotCentered(
                            AdditiveRobotCenteredPhysicsFaultConfig::default(),
                        ))
                    },
                    _ => panic!("Where did you find this fault?"),
                };
            }
        });
    }

    /// Renders a read-only GUI view for a list of physics fault model configurations.
    pub fn show_faults(
        faults: &[PhysicsFaultModelConfig],
        ui: &mut egui::Ui,
        ctx: &egui::Context,
        unique_id: &str,
    ) {
        ui.label("Faults:");
        for (i, fault) in faults.iter().enumerate() {
            ui.horizontal_top(|ui| {
                let unique_fault_id = format!("physics-fault-{i}-{unique_id}");
                fault.show(ui, ctx, &unique_fault_id);
            });
        }
    }
}

/// Creates a runtime physics fault model from [`PhysicsFaultModelConfig`].
pub fn make_physics_fault_model_from_config(
    config: &PhysicsFaultModelConfig,
    robot_model: RobotModelConfig,
    _robot_name: &String,
    va_factory: &Arc<DeterministRandomVariableFactory>,
    initial_time: f32,
) -> Box<dyn PhysicsFaultModel> {
    match &config {
        PhysicsFaultModelConfig::AdditiveRobotCentered(cfg) => {
            Box::new(AdditiveRobotCenteredPhysicsFault::from_config(
                cfg,
                robot_model,
                va_factory,
                initial_time,
            )) as Box<dyn PhysicsFaultModel>
        }
    }
}

/// Trait implemented by all physics fault models.
pub trait PhysicsFaultModel: Debug + Sync + Send {
    /// Optional initialization hook called once before simulation steps.
    fn post_init(&mut self, _node: &mut crate::node::Node) -> SimbaResult<()> {
        Ok(())
    }

    /// Applies physics faults to the mutable state at the provided simulation time.
    fn add_faults(&self, time: f32, state: &mut State);
}
